name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Execute tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Composer dependencies & start test
        run: |
          composer install --no-progress --no-suggest --prefer-dist
          php bin/phpunit

  lint:
    name: Execute lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Composer dependencies & start lint
        run: |
          composer install --no-progress --no-suggest --prefer-dist
          composer exec phpcs

  build:
    name: Build app
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Composer dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
